import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,Clock3,MapPin,Phone,MessageCircle,ShieldCheck,Settings,LayoutDashboard,CalendarCheck,Wallet,ReceiptText,ImagePlus,Info,LogOut,Plus,Trash2,Pencil,CheckCircle2,XCircle,Sun,Moon,ChevronRight,RefreshCw,Menu,X,LockKeyhole,Save,Search,ExternalLink} from 'lucide-react';
import {auth,db,firebaseMissingConfig} from './firebase';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import {collection,doc,getDoc,onSnapshot,query,orderBy,setDoc,serverTimestamp,deleteDoc,runTransaction,getDocs,where} from 'firebase/firestore';

const TZ=import.meta.env.VITE_TURF_TIMEZONE||'Asia/Dhaka';
const pad=n=>String(n).padStart(2,'0');
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=n=>`৳${Number(n||0).toLocaleString('en-BD',{maximumFractionDigits:3})}`;
const timeLabel=t=>{if(!t)return '';const [h,m]=t.split(':').map(Number);return `${h%12||12}:${pad(m)} ${h>=12?'PM':'AM'}`};
const mins=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m};
const addM=(t,n)=>{let x=(mins(t)+n)%1440;return `${pad(Math.floor(x/60))}:${pad(x%60)}`};
const absM=t=>mins(t)+(mins(t)<mins('06:00')?1440:0);
function generateSlots(date,settings){const duration=Number(settings?.slotDuration);if(![60,90].includes(duration))return [];const open=settings.openingTime||'06:00',close=settings.closingTime||'04:00',dayBoundary=settings.dayBoundary||(duration===60?'18:00':'16:30');const out=[];for(let m=absM(open);m+duration<=absM(close);m+=duration){const s=`${pad(Math.floor((m%1440)/60))}:${pad(m%60)}`,e=addM(s,duration);const shift=(absM(s)+duration<=mins(dayBoundary))?'day':'night';out.push({date,start:s,end:e,duration,shift,key:`${date}_${s.replace(':','')}_${duration}`});}return out}
function useDoc(path,initial={}){const [data,setData]=useState(initial),[loading,setLoading]=useState(true);useEffect(()=>onSnapshot(doc(db,...path.split('/')),s=>{setData(s.exists()?s.data():initial);setLoading(false)},()=>setLoading(false)),[]);return [data,loading]}
function useCollection(name,enabled=true){const [data,setData]=useState([]);useEffect(()=>{if(!enabled)return;return onSnapshot(query(collection(db,name),orderBy('createdAt','desc')),s=>setData(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setData([]))},[name,enabled]);return data}
function Loading(){return <div className="loading"><div className="ball">⚽</div><span>Loading TurfClub…</span></div>}
function Empty({title='No data available',text=''}){return <div className="empty"><div className="empty-icon">⚽</div><b>{title}</b>{text&&<span>{text}</span>}</div>}
function Modal({title,onClose,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><h3>{title}</h3></div><button className="icon-btn" onClick={onClose}><X/></button></div>{children}</div></div>}
function App(){
 const [route,setRoute]=useState(window.location.pathname),[admin,setAdmin]=useState(null),[authLoading,setAuthLoading]=useState(true);
 useEffect(()=>onAuthStateChanged(auth,u=>{setAdmin(u);setAuthLoading(false)}),[]);
 useEffect(()=>{const f=()=>setRoute(window.location.pathname);window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);
 const go=p=>{window.history.pushState({},'',p);setRoute(p)};
 if(firebaseMissingConfig.length)return <div className="config-error"><h1>TurfClub</h1><p>Firebase configuration is missing.</p><code>{firebaseMissingConfig.join('\n')}</code><p>Add the values from <b>.env.example</b> to your deployment environment.</p></div>;
 if(authLoading)return <Loading/>;
 if(route.startsWith('/admin'))return admin?<AdminShell user={admin} go={go}/>:<AdminLogin/>;
 return <PublicSite go={go}/>;
}
function PublicSite({go}){
 const [turf]=useDoc('turf/main'),[settings]=useDoc('settings/config'),[pricing]=useDoc('pricing/current'),[date,setDate]=useState(localDate()),[shift,setShift]=useState('day'),[booked,setBooked]=useState([]),[selected,setSelected]=useState(null),[notice,setNotice]=useState(null),[menuOpen,setMenuOpen]=useState(false);
 const gallery=useCollection('gallery');
 useEffect(()=>onSnapshot(query(collection(db,'slotLocks'),where('sessionDate','==',date)),s=>setBooked(s.docs.map(d=>d.id)),()=>setBooked([])),[date]);
 const slots=useMemo(()=>generateSlots(date,settings).filter(s=>s.shift===shift),[date,settings,shift]);
 const price=s=>{const direct=pricing?.rules?.[String(s.duration)]?.[s.shift];if(direct!=null)return Number(direct);const r=(pricing?.timeRanges||[]).find(x=>Number(x.duration)===s.duration&&mins(s.start)>=mins(x.start)&&mins(s.start)<mins(x.end));return r?Number(r.price):0};
 const jump=id=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})};
 return <div className="public"><header className="public-nav"><button className="brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><span className="brand-ball">⚽</span>Turf<span>Club</span></button><nav><button onClick={()=>jump('book')}>Book</button><button onClick={()=>jump('info')}>Turf</button><button onClick={()=>jump('gallery')}>Gallery</button><button onClick={()=>jump('location')}>Location</button></nav><button className="public-menu" aria-label="Open navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X/>:<Menu/>}</button></header>{menuOpen&&<div className="public-mobile-nav"><button onClick={()=>jump('book')}>Book a Slot</button><button onClick={()=>jump('info')}>Turf Information</button><button onClick={()=>jump('gallery')}>Gallery</button><button onClick={()=>jump('location')}>Location</button></div>}
 <section className="hero"><div className="pitch-glow"/><div className="hero-copy"><div className="eyebrow">⚽ PREMIUM FOOTBALL TURF</div><h1>{turf.name||'Your Football Turf'}</h1><p>{turf.description||'Book your next football session with a fast, simple and real-time slot experience.'}</p><button className="primary" onClick={()=>document.getElementById('book')?.scrollIntoView({behavior:'smooth'})}>Book a Slot <ChevronRight/></button></div><div className="hero-card"><div className="scoreline"><span>OPEN</span><strong>{settings.openingTime||'06:00'} — {settings.closingTime||'04:00'}</strong></div><div className="hero-stat"><b>{settings.slotDuration||'—'}</b><span>minute sessions</span></div><div className="hero-stat"><b>LIVE</b><span>availability</span></div></div></section>
 <section id="book" className="section"><div className="section-title"><div><span className="eyebrow">BOOKING CENTRE</span><h2>Choose your slot</h2></div><div className="date-picker"><CalendarDays/><input type="date" value={date} min={localDate()} onChange={e=>setDate(e.target.value)}/></div></div><div className="shift-toggle"><button className={shift==='day'?'active':''} onClick={()=>setShift('day')}><Sun/>DAY</button><button className={shift==='night'?'active':''} onClick={()=>setShift('night')}><Moon/>NIGHT</button></div><div className="slot-grid">{slots.map(s=>{const isBooked=booked.includes(s.key);return <button key={s.key} disabled={isBooked} className={`slot ${isBooked?'booked':''}`} onClick={()=>setSelected({...s,price:price(s)})}><div><b>{timeLabel(s.start)}</b><span>to {timeLabel(s.end)}</span></div><div className="slot-right"><small>{s.duration} MIN · {s.shift.toUpperCase()}</small><strong>{price(s)?money(price(s)):'Price unavailable'}</strong><em>{isBooked?'BOOKED':'AVAILABLE'}</em></div></button>})}</div>{!slots.length&&<Empty title="Slots are not configured yet" text="The turf owner needs to configure operating hours and slot duration."/>}</section>
 <section id="info" className="section alt"><div className="section-title"><div><span className="eyebrow">THE TURF</span><h2>Everything you need</h2></div></div><div className="info-grid"><InfoCard title="Facilities" text={(turf.facilities||[]).join(' • ')||'No facilities listed yet.'}/><InfoCard title="Rules" text={(turf.rules||[]).join(' • ')||'No rules listed yet.'}/><InfoCard title="Contact" text={turf.phone?`Phone: ${turf.phone}${turf.whatsapp?` · WhatsApp: ${turf.whatsapp}`:''}`:(turf.contactNote||'Contact the turf owner for assistance.')}/></div></section>
 <section id="gallery" className="section"><div className="section-title"><div><span className="eyebrow">GALLERY</span><h2>Inside TurfClub</h2></div></div>{gallery.length?<div className="gallery">{gallery.map(g=><img key={g.id} src={g.url} alt={g.alt||'TurfClub'}/>)}</div>:<Empty title="No turf photos available yet"/>}</section>
 <section id="location" className="section alt"><div className="location-card"><div><span className="eyebrow">LOCATION</span><h2>{turf.address||'Location not configured'}</h2><p>{turf.locationNote||'The turf owner has not added location details yet.'}</p></div>{turf.mapsUrl&&<a className="primary" href={turf.mapsUrl} target="_blank" rel="noreferrer">Open Maps <ExternalLink/></a>}</div></section>
 <footer><span>⚽ TurfClub</span><span>© {new Date().getFullYear()} TurfClub</span></footer>
 {selected&&<BookingModal slot={selected} onClose={()=>setSelected(null)} onDone={r=>{setSelected(null);setNotice({...r,date:selected.date,start:selected.start})}}/>}{notice&&<Modal title="Booking confirmed" onClose={()=>setNotice(null)}><div className="success"><CheckCircle2/><h3>Your slot is booked</h3><p>Booking ID: <b>{notice.bookingId}</b></p><p>{notice.date} · {timeLabel(notice.start)} — {timeLabel(notice.slotEnd)}</p><strong>{money(notice.slotPrice)}</strong></div></Modal>}
 </div>
}
function InfoCard({title,text}){return <div className="info-card"><h3>{title}</h3><p>{text}</p></div>}
async function createBookingClient(slot,form){
 const settings=(await getDoc(doc(db,'settings/config'))).data()||{};
 const pricing=(await getDoc(doc(db,'pricing/current'))).data()||{};
 const duration=Number(settings.slotDuration||slot.duration); if(![60,90].includes(duration)) throw new Error('Slot duration is not configured.');
 const start=String(slot.start); const end=addM(start,duration); const shift=String(slot.shift); const direct=pricing?.rules?.[String(duration)]?.[shift]; const range=(pricing?.timeRanges||[]).find(x=>Number(x.duration)===duration&&mins(start)>=mins(x.start)&&mins(start)<mins(x.end)); const price=direct!=null?Number(direct):(range?Number(range.price):0); if(price<=0) throw new Error('This slot does not have a configured price.');
 const advance=Math.max(0,Number(form.advanceAmount||0)); if(advance>price) throw new Error('Advance cannot exceed slot price.');
 const slotKey=`${slot.date}_${start.replace(':','')}_${duration}`; const lockRef=doc(db,'slotLocks',slotKey); const bookingRef=doc(collection(db,'bookings')); const paymentRef=advance?doc(collection(db,'payments')):null; const txRef=advance?doc(collection(db,'transactions')):null;
 await runTransaction(db,async tx=>{const lock=await tx.get(lockRef);if(lock.exists()&&lock.data().status==='booked')throw new Error('That slot was just booked. Please choose another slot.');const now=serverTimestamp();tx.set(lockRef,{status:'booked',bookingId:bookingRef.id,slotKey,sessionDate:slot.date,slotStart:start,slotEnd:end,duration,shift,createdAt:now,updatedAt:now});tx.set(bookingRef,{customerName:String(form.customerName||'').trim(),phone:String(form.phone||'').trim(),date:slot.date,sessionDate:slot.date,slotStart:start,slotEnd:end,duration,shift,slotPrice:price,totalAmount:price,paidAmount:advance,advanceAmount:advance,remainingAmount:price-advance,dueAmount:price-advance,status:'confirmed',slotKey,createdBy:'public',createdAt:now,updatedAt:now});if(paymentRef)tx.set(paymentRef,{bookingId:bookingRef.id,amount:advance,paymentMethod:String(form.paymentMethod||'Other'),paymentDate:slot.date,note:'Booking advance',createdAt:now,createdBy:'public'});if(txRef)tx.set(txRef,{type:'income',amount:advance,category:'Booking payment',referenceId:bookingRef.id,description:`Advance for ${String(form.customerName||'').trim()} ${slot.date} ${start}`,date:slot.date,createdAt:now,createdBy:'public'});});
 return {bookingId:bookingRef.id,slotEnd:end,slotPrice:price,remainingAmount:price-advance,status:'confirmed'};
}
async function recordPaymentClient({bookingId,amount,paymentMethod,paymentDate,note}){
 const bookingRef=doc(db,'bookings',bookingId),paymentRef=doc(collection(db,'payments')),txRef=doc(collection(db,'transactions')); const n=Math.round(Number(amount||0)*1000)/1000; if(n<=0)throw new Error('Payment must be greater than zero.');
 await runTransaction(db,async tx=>{const snap=await tx.get(bookingRef);if(!snap.exists())throw new Error('Booking not found.');const b=snap.data();if(b.status==='cancelled')throw new Error('Cancelled bookings cannot receive payments.');const total=Number(b.totalAmount||b.slotPrice||0),paid=Number(b.paidAmount||0);if(paid+n>total)throw new Error('Payment exceeds the remaining due.');const now=serverTimestamp(),newPaid=paid+n;tx.update(bookingRef,{paidAmount:newPaid,advanceAmount:Number(b.advanceAmount||0),remainingAmount:total-newPaid,dueAmount:total-newPaid,updatedAt:now});tx.set(paymentRef,{bookingId,amount:n,paymentMethod:String(paymentMethod||'Other'),paymentDate:String(paymentDate||b.sessionDate),note:String(note||''),createdAt:now,createdBy:auth.currentUser.uid});tx.set(txRef,{type:'income',amount:n,category:'Booking payment',referenceId:bookingId,description:`Payment for booking ${bookingId}`,date:String(paymentDate||b.sessionDate),createdAt:now,createdBy:auth.currentUser.uid});});
}
async function cancelBookingClient(bookingId){const bookingRef=doc(db,'bookings',bookingId);await runTransaction(db,async tx=>{const snap=await tx.get(bookingRef);if(!snap.exists())throw new Error('Booking not found.');const b=snap.data();if(b.status==='cancelled')return;tx.update(bookingRef,{status:'cancelled',updatedAt:serverTimestamp(),cancelledAt:serverTimestamp(),cancelledBy:auth.currentUser.uid});if(b.slotKey)tx.delete(doc(db,'slotLocks',b.slotKey));});}
async function createExpenseClient(f){const expenseRef=doc(collection(db,'expenses')),txRef=doc(collection(db,'transactions'));await runTransaction(db,async tx=>{const now=serverTimestamp();tx.set(expenseRef,{reason:String(f.reason||'').trim(),amount:Number(f.amount),date:String(f.date),category:String(f.category||'Other'),note:String(f.note||''),createdAt:now,updatedAt:now,createdBy:auth.currentUser.uid});tx.set(txRef,{type:'expense',amount:Number(f.amount),category:String(f.category||'Other'),referenceId:expenseRef.id,description:String(f.reason||'').trim(),date:String(f.date),createdAt:now,createdBy:auth.currentUser.uid});});}
async function updateExpenseClient(item,f){const expenseRef=doc(db,'expenses',item.id);const qs=await getDocs(query(collection(db,'transactions'),where('referenceId','==',item.id),where('type','==','expense')));const txRef=qs.empty?doc(collection(db,'transactions')):qs.docs[0].ref;await runTransaction(db,async tx=>{const now=serverTimestamp();tx.update(expenseRef,{reason:String(f.reason||'').trim(),amount:Number(f.amount),date:String(f.date),category:String(f.category||'Other'),note:String(f.note||''),updatedAt:now,updatedBy:auth.currentUser.uid});tx.set(txRef,{type:'expense',amount:Number(f.amount),category:String(f.category||'Other'),referenceId:item.id,description:String(f.reason||'').trim(),date:String(f.date),updatedAt:now,createdAt:item.createdAt||now,createdBy:item.createdBy||auth.currentUser.uid,updatedBy:auth.currentUser.uid},{merge:true});});}
async function deleteExpenseClient(id){const expenseRef=doc(db,'expenses',id);const qs=await getDocs(query(collection(db,'transactions'),where('referenceId','==',id),where('type','==','expense')));await runTransaction(db,async tx=>{tx.delete(expenseRef);qs.forEach(x=>tx.delete(x.ref));});}
async function addGalleryUrlClient(url,alt){const u=String(url||'').trim();if(!/^https?:\/\//i.test(u))throw new Error('Please enter a valid http(s) image URL.');await setDoc(doc(collection(db,'gallery')),{url:u,alt:String(alt||'TurfClub turf photo'),createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});}
function BookingModal({slot,onClose,onDone}){const [form,setForm]=useState({customerName:'',phone:'',advanceAmount:'',paymentMethod:'Cash'}),[busy,setBusy]=useState(false),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);setErr('');try{const r=await createBookingClient(slot,form);onDone(r.data)}catch(x){setErr(x.message||'Booking failed. Please try again.')}finally{setBusy(false)}};return <Modal title="Book your football session" onClose={onClose}><form onSubmit={submit} className="form"><div className="booking-summary"><span>{slot.date}</span><b>{timeLabel(slot.start)} — {timeLabel(slot.end)}</b><span>{slot.duration} minutes · {slot.shift.toUpperCase()}</span><strong>{money(slot.price)}</strong></div><label>Customer name<input required minLength="2" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></label><label>Phone number<input required minLength="5" inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Advance amount<input type="number" min="0" max={slot.price} step="0.001" value={form.advanceAmount} onChange={e=>setForm({...form,advanceAmount:e.target.value})}/></label><label>Payment method<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option>Cash</option><option>Mobile Banking</option><option>Bank Transfer</option><option>Other</option></select></label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?'Booking…':'Confirm booking'} <CheckCircle2/></button></form></Modal>}
function AdminLogin(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);setErr('');try{await signInWithEmailAndPassword(auth,email,password)}catch(x){setErr('Sign-in failed. Check your admin credentials.')}finally{setBusy(false)}};return <div className="admin-login"><div className="login-card"><div className="brand big"><span className="brand-ball">⚽</span>Turf<span>Club</span></div><span className="eyebrow">ADMIN PORTAL</span><h1>Owner sign in</h1><p>Manage bookings, slots and finances securely.</p><form className="form" onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in'} <LockKeyhole/></button></form></div></div>}
function AdminShell({user,go}){const [page,setPage]=useState(window.location.pathname.split('/')[2]||'dashboard'),[open,setOpen]=useState(false);const nav=[['dashboard','Dashboard',LayoutDashboard],['bookings','Bookings',CalendarCheck],['finance','Finance',Wallet],['expenses','Expenses',ReceiptText],['gallery','Gallery',ImagePlus],['turf','Turf Information',Info],['pricing','Pricing',Settings]];const select=p=>{setPage(p);go('/admin/'+p);setOpen(false)};return <div className="admin-app"><aside className={open?'open':''}><div className="brand"><span className="brand-ball">⚽</span>Turf<span>Club</span></div><div className="admin-user"><b>{user.email}</b><span>Administrator</span></div>{nav.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>select(id)}><I/>{label}</button>)}<button className="signout" onClick={()=>signOut(auth)}><LogOut/>Sign out</button></aside><main className="admin-main"><header className="admin-header"><button className="icon-btn mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div><span className="eyebrow">TURF MANAGEMENT</span><h1>{nav.find(n=>n[0]===page)?.[1]||'Dashboard'}</h1></div></header>{page==='dashboard'&&<Dashboard go={go}/>} {page==='bookings'&&<Bookings/>}{page==='finance'&&<Finance/>}{page==='expenses'&&<Expenses/>}{page==='gallery'&&<GalleryAdmin/>}{page==='turf'&&<TurgAdmin/>}{page==='pricing'&&<PricingAdmin/>}</main></div>}
function Dashboard(){const [settings]=useDoc('settings/config'),bookings=useCollection('bookings'),payments=useCollection('payments'),expenses=useCollection('expenses');const today=localDate(),month=today.slice(0,7),year=today.slice(0,4);const sum=(arr,field,datePrefix)=>arr.filter(x=>String(x[datePrefix||'date']||x.sessionDate||'').startsWith(datePrefix)).reduce((a,x)=>a+Number(x[field]||0),0);const bToday=bookings.filter(b=>b.sessionDate===today&&b.status!=='cancelled').length,bMonth=bookings.filter(b=>String(b.sessionDate||'').startsWith(month)&&b.status!=='cancelled').length,bYear=bookings.filter(b=>String(b.sessionDate||'').startsWith(year)&&b.status!=='cancelled').length;const pToday=payments.filter(p=>p.paymentDate===today).reduce((a,p)=>a+Number(p.amount||0),0),pMonth=payments.filter(p=>String(p.paymentDate||'').startsWith(month)).reduce((a,p)=>a+Number(p.amount||0),0),pYear=payments.filter(p=>String(p.paymentDate||'').startsWith(year)).reduce((a,p)=>a+Number(p.amount||0),0);const eToday=expenses.filter(x=>x.date===today).reduce((a,x)=>a+Number(x.amount||0),0),eMonth=expenses.filter(x=>String(x.date||'').startsWith(month)).reduce((a,x)=>a+Number(x.amount||0),0),eYear=expenses.filter(x=>String(x.date||'').startsWith(year)).reduce((a,x)=>a+Number(x.amount||0),0);return <><div className="welcome"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>{settings.turfName||'TurfClub'} command centre</h2><p>Real bookings, payments and costs from Firebase.</p></div></div><div className="period-grid"><Period title="TODAY" bookings={bToday} collected={pToday} expenses={eToday}/><Period title="THIS MONTH" bookings={bMonth} collected={pMonth} expenses={eMonth}/><Period title="THIS YEAR" bookings={bYear} collected={pYear} expenses={eYear}/></div></>}
function Period({title,bookings,collected,expenses}){return <div className="period-card"><span>{title}</span><div className="period-main"><div><b>{bookings}</b><small>Slot bookings</small></div><div><b>{money(collected)}</b><small>Collected</small></div><div><b>{money(expenses)}</b><small>Expenses</small></div><div className="net"><b>{money(collected-expenses)}</b><small>Net revenue</small></div></div></div>}
function Bookings(){const bookings=useCollection('bookings'),payments=useCollection('payments'),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[modal,setModal]=useState(null);const rows=bookings.filter(b=>(status==='all'||b.status===status)&&`${b.customerName} ${b.phone} ${b.id}`.toLowerCase().includes(q.toLowerCase()));return <><div className="toolbar"><div className="search"><Search/><input placeholder="Search customer, phone or booking ID" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option>confirmed</option><option>cancelled</option><option>completed</option><option>pending</option></select></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Customer</th><th>Slot</th><th>Value</th><th>Paid</th><th>Due</th><th>Status</th><th/></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td>{b.sessionDate}</td><td><b>{b.customerName}</b><small>{b.phone}</small></td><td>{timeLabel(b.slotStart)}–{timeLabel(b.slotEnd)}</td><td>{money(b.totalAmount)}</td><td>{money(b.paidAmount)}</td><td>{money(b.dueAmount)}</td><td><span className={`badge ${b.status}`}>{b.status}</span></td><td><div className="row-actions">{b.status!=='cancelled'&&Number(b.dueAmount)>0&&<button className="small" onClick={()=>setModal({type:'payment',booking:b})}>Payment</button>}{b.status!=='cancelled'&&<button className="small danger" onClick={()=>setModal({type:'cancel',booking:b})}>Cancel</button>}</div></td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>{modal?.type==='payment'&&<PaymentModal booking={modal.booking} onClose={()=>setModal(null)}/>} {modal?.type==='cancel'&&<ConfirmModal title="Cancel booking?" text="The booking will become cancelled and its slot will become available again." onClose={()=>setModal(null)} onConfirm={async()=>{await cancelBookingClient(modal.booking.id);setModal(null)}}/>}</>}
function PaymentModal({booking,onClose}){const [amount,setAmount]=useState(booking.dueAmount),[method,setMethod]=useState('Cash'),[date,setDate]=useState(localDate()),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setBusy(true);try{await recordPaymentClient({bookingId:booking.id,amount:Number(amount),paymentMethod:method,paymentDate:date,note});onClose()}catch(x){setErr(x.message||'Payment failed.')}finally{setBusy(false)}};return <Modal title="Record payment" onClose={onClose}><form className="form" onSubmit={submit}><div className="booking-summary"><span>Due</span><strong>{money(booking.dueAmount)}</strong></div><label>Amount<input type="number" min="0.001" max={booking.dueAmount} step="0.001" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option>Cash</option><option>Mobile Banking</option><option>Bank Transfer</option><option>Other</option></select></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?'Saving…':'Record payment'} <Save/></button></form></Modal>}
function ConfirmModal({title,text,onClose,onConfirm}){const [busy,setBusy]=useState(false);return <Modal title={title} onClose={onClose}><p>{text}</p><div className="modal-actions"><button className="secondary" onClick={onClose}>Keep booking</button><button className="danger-btn" disabled={busy} onClick={async()=>{setBusy(true);await onConfirm();setBusy(false)}}>{busy?'Working…':'Confirm cancel'}</button></div></Modal>}
function Finance(){const payments=useCollection('payments'),expenses=useCollection('expenses'),bookings=useCollection('bookings'),[date,setDate]=useState(localDate()),month=date.slice(0,7),year=date.slice(0,4);const p=payments.filter(x=>x.paymentDate===date).reduce((a,x)=>a+Number(x.amount||0),0),e=expenses.filter(x=>x.date===date).reduce((a,x)=>a+Number(x.amount||0),0),pm=payments.filter(x=>String(x.paymentDate||'').startsWith(month)).reduce((a,x)=>a+Number(x.amount||0),0),em=expenses.filter(x=>String(x.date||'').startsWith(month)).reduce((a,x)=>a+Number(x.amount||0),0),py=payments.filter(x=>String(x.paymentDate||'').startsWith(year)).reduce((a,x)=>a+Number(x.amount||0),0),ey=expenses.filter(x=>String(x.date||'').startsWith(year)).reduce((a,x)=>a+Number(x.amount||0),0),bd=bookings.filter(x=>x.sessionDate===date&&x.status!=='cancelled').length,bm=bookings.filter(x=>String(x.sessionDate||'').startsWith(month)&&x.status!=='cancelled').length,by=bookings.filter(x=>String(x.sessionDate||'').startsWith(year)&&x.status!=='cancelled').length;const cats={};expenses.filter(x=>String(x.date||'').startsWith(month)).forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount||0));return <><div className="report-controls"><label>Daily report date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="period-grid"><Period title={date===localDate()?'TODAY':date} bookings={bd} collected={p} expenses={e}/><Period title={month} bookings={bm} collected={pm} expenses={em}/><Period title={year} bookings={by} collected={py} expenses={ey}/></div><div className="two-col"><div className="panel"><h3>Expense breakdown · {month}</h3>{Object.entries(cats).length?Object.entries(cats).map(([k,v])=><div className="breakdown" key={k}><span>{k}</span><b>{money(v)}</b></div>):<Empty title="No expenses"/>}</div><div className="panel"><h3>Transaction ledger</h3>{payments.length||expenses.length?[...payments.map(p=>({type:'income',date:p.paymentDate,amount:p.amount,desc:'Booking payment',id:p.id})),...expenses.map(e=>({type:'expense',date:e.date,amount:e.amount,desc:e.reason,id:e.id}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,30).map(x=><div className="ledger" key={x.id}><span>{x.type==='income'?'+':'−'} {x.desc}<small>{x.date}</small></span><b className={x.type}>{x.type==='income'?'+':'−'}{money(x.amount)}</b></div>):<Empty/>}</div></div></>}
function Expenses(){const expenses=useCollection('expenses'),[modal,setModal]=useState(null),[q,setQ]=useState('');const rows=expenses.filter(x=>`${x.reason} ${x.category} ${x.note}`.toLowerCase().includes(q.toLowerCase()));return <><div className="toolbar"><div className="search"><Search/><input placeholder="Search reason or category" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="primary" onClick={()=>setModal({})}><Plus/> Add expense</button></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reason</th><th>Category</th><th>Amount</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.reason}</b><small>{x.note}</small></td><td>{x.category}</td><td><b>{money(x.amount)}</b></td><td><div className="row-actions"><button className="small" onClick={()=>setModal(x)}><Pencil/></button><button className="small danger" onClick={async()=>{if(confirm('Delete this expense?'))await deleteExpenseClient(x.id)}}><Trash2/></button></div></td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>{modal&&<ExpenseModal item={modal.id?modal:null} onClose={()=>setModal(null)}/>}</>}
function ExpenseModal({item,onClose}){const [f,setF]=useState(item||{reason:'',amount:'',date:localDate(),category:'Other',note:''}),[busy,setBusy]=useState(false),[err,setErr]=useState('');const save=async e=>{e.preventDefault();setBusy(true);try{item?await updateExpenseClient(item,{...f,amount:Number(f.amount)}):await createExpenseClient({...f,amount:Number(f.amount)});onClose()}catch(x){setErr(x.message||'Could not save expense.')}finally{setBusy(false)}};return <Modal title={item?'Edit expense':'Add expense'} onClose={onClose}><form className="form" onSubmit={save}><label>Reason<input required value={f.reason} onChange={e=>setF({...f,reason:e.target.value})}/></label><label>Amount<input type="number" min="0.001" step="0.001" required value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Date<input type="date" required value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{['Staff Cost','Electricity Cost','Rent','Maintenance','Equipment','Cleaning','Marketing','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Note<input value={f.note} onChange={e=>setF({...f,note:e.target.value})}/></label>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?'Saving…':'Save expense'} <Save/></button></form></Modal>}
function GalleryAdmin(){const items=useCollection('gallery'),[url,setUrl]=useState(''),[alt,setAlt]=useState('TurfClub turf photo'),[busy,setBusy]=useState(false);const add=async e=>{e.preventDefault();setBusy(true);try{await addGalleryUrlClient(url,alt);setUrl('')}catch(err){alert(err.message||'Could not add image.')}finally{setBusy(false)}};return <><form className="toolbar gallery-url-form" onSubmit={add}><input placeholder="Public image URL (https://...)" value={url} onChange={e=>setUrl(e.target.value)} required/><input placeholder="Alt text" value={alt} onChange={e=>setAlt(e.target.value)}/><button className="primary" disabled={busy}>{busy?'Adding…':'Add photo URL'} <Plus/></button></form>{items.length?<div className="gallery admin-gallery">{items.map(x=><div className="gallery-item" key={x.id}><img src={x.url} alt={x.alt}/><button className="danger-float" onClick={async()=>{if(confirm('Delete photo?'))await deleteDoc(doc(db,'gallery',x.id))}}><Trash2/></button></div>)}</div>:<Empty title="No turf photos available yet" text="Add images using a public image URL."/>}</>}
function TurgAdmin(){const [turf,setTurf]=useState({}),[settings,setSettings]=useState({}),[saving,setSaving]=useState(false);useEffect(()=>Promise.all([getDoc(doc(db,'turf/main')),getDoc(doc(db,'settings/config'))]).then(([a,b])=>{setTurf(a.exists()?a.data():{});setSettings(b.exists()?b.data():{})}),[]);const save=async()=>{setSaving(true);try{await setDoc(doc(db,'turf/main'),{...turf,updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,'settings/config'),{...settings,updatedAt:serverTimestamp()},{merge:true});alert('Saved')}finally{setSaving(false)}};return <div className="two-col"><div className="panel"><h3>Turf information</h3><div className="form"><label>Name<input value={turf.name||''} onChange={e=>setTurf({...turf,name:e.target.value})}/></label><label>Description<textarea value={turf.description||''} onChange={e=>setTurf({...turf,description:e.target.value})}/></label><label>Address<input value={turf.address||''} onChange={e=>setTurf({...turf,address:e.target.value})}/></label><label>Google Maps URL<input value={turf.mapsUrl||''} onChange={e=>setTurf({...turf,mapsUrl:e.target.value})}/></label><label>Phone<input value={turf.phone||''} onChange={e=>setTurf({...turf,phone:e.target.value})}/></label><label>WhatsApp<input value={turf.whatsapp||''} onChange={e=>setTurf({...turf,whatsapp:e.target.value})}/></label><label>Facilities <small>one per line</small><textarea value={(turf.facilities||[]).join('\n')} onChange={e=>setTurf({...turf,facilities:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/></label><label>Rules <small>one per line</small><textarea value={(turf.rules||[]).join('\n')} onChange={e=>setTurf({...turf,rules:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/></label></div></div><div className="panel"><h3>Operating hours</h3><div className="form"><label>Opening time<input type="time" value={settings.openingTime||'06:00'} onChange={e=>setSettings({...settings,openingTime:e.target.value})}/></label><label>Closing time<input type="time" value={settings.closingTime||'04:00'} onChange={e=>setSettings({...settings,closingTime:e.target.value})}/></label><label>Slot duration<select value={settings.slotDuration||60} onChange={e=>setSettings({...settings,slotDuration:Number(e.target.value),dayBoundary:Number(e.target.value)===60?'18:00':'16:30'})}><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><label>Day boundary<input type="time" value={settings.dayBoundary||''} onChange={e=>setSettings({...settings,dayBoundary:e.target.value})}/></label><button className="primary full" onClick={save} disabled={saving}>{saving?'Saving…':'Save configuration'} <Save/></button></div></div></div>}
function PricingAdmin(){const [p,setP]=useState({rules:{'60':{day:'','night':''},'90':{day:'','night':''}},timeRanges:[]}),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false);useEffect(()=>getDoc(doc(db,'pricing/current')).then(s=>{if(s.exists())setP(s.data());setLoaded(true)}),[]);const save=async()=>{setSaving(true);try{await setDoc(doc(db,'pricing/current'),{...p,updatedAt:serverTimestamp()},{merge:true});alert('Pricing saved')}finally{setSaving(false)}};if(!loaded)return <Loading/>;return <div className="panel narrow"><h3>Shift pricing</h3><p className="muted">Configure prices for both allowed slot durations and day/night. The live booking checks the current Firestore pricing before confirming the slot.</p><div className="price-grid">{[60,90].map(d=><React.Fragment key={d}><div className="price-label">{d} minutes · DAY</div><input type="number" min="0" step="0.001" value={p.rules?.[d]?.day??''} onChange={e=>setP({...p,rules:{...p.rules,[d]:{...(p.rules?.[d]||{}),day:e.target.value}}})}/><div className="price-label">{d} minutes · NIGHT</div><input type="number" min="0" step="0.001" value={p.rules?.[d]?.night??''} onChange={e=>setP({...p,rules:{...p.rules,[d]:{...(p.rules?.[d]||{}),night:e.target.value}}})}/></React.Fragment>)}</div><button className="primary full" onClick={save} disabled={saving}>{saving?'Saving…':'Save pricing'} <Save/></button></div>}

export default App;
